# @package _group_
type: 'camels-gb'
features: {'timeseries' : ['precipitation', 'temperature', 'windspeed', 'shortwave_rad']}
seq_length: 365 # Number of previous days of meterological data to use for one prediction.
train_test_split: '2010' # Split date to separate the data into the train and test sets.
basins_frac: 0.1 # Fraction of basins that will be combined to create the dataset.
num_workers: 8 # Number of subprocesses to use for data loading.
